package car.parts

import com.pi4j.gpio.extension.mcp.MCP23S17Pin.*

/* == From MCP23S17(IC0) to Rear BTS7960 bridges == */
val REAR_RIGHT_BRIDGE_ENABLER_PIN = GPIO_B4
val REAR_LEFT_BRIDGE_ENABLER_PIN = GPIO_B3

/* == From MCP23S17(IC0) to Front BTS7960 bridges == */
val FRONT_RIGHT_BRIDGE_ENABLER_PIN = GPIO_A4
val FRONT_LEFT_BRIDGE_ENABLER_PIN = GPIO_A3

/* == From MCP23S17(IC0) to Rear 74HC4053(IC1) == */
val REAR_MULTIPLEXER_SELECTOR_1 = GPIO_B0
val REAR_MULTIPLEXER_SELECTOR_2 = GPIO_B1
val REAR_MULTIPLEXER_SELECTOR_3 = GPIO_B2

/* == From MCP23S17(IC0) to Front 74HC4053(IC0) == */
val FRONT_MULTIPLEXER_SELECTOR_1 = GPIO_A0
val FRONT_MULTIPLEXER_SELECTOR_2 = GPIO_A1
val FRONT_MULTIPLEXER_SELECTOR_3 = GPIO_A2